(FUNCTION  putDigit  [(int s)]
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 2)]  [(i 48)])
    (OPER 5 Add_I [(r 3)]  [(r 2)(r 1)])
    (OPER 6 Pass []  [(r 3)] [(PARAM_NUM 0)])
    (OPER 7 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 8 Mov [(r 4)]  [(m RetReg)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
)
(FUNCTION  printInt  [(int x)]
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 4)]  [(i 0)])
    (OPER 5 LT [(r 5)]  [(r 1)(r 4)])
    (OPER 6 BEQ []  [(r 5)(i 0)(bb 5)])
  )
  (BB 4
    (OPER 7 Mov [(r 6)]  [(i 45)])
    (OPER 8 Pass []  [(r 6)] [(PARAM_NUM 0)])
    (OPER 9 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 10 Mov [(r 7)]  [(m RetReg)])
    (OPER 11 Mov [(r 8)]  [(i 0)])
    (OPER 12 Sub_I [(r 9)]  [(r 8)(r 1)])
    (OPER 13 Mov [(r 1)]  [(r 9)])
  )
  (BB 5
    (OPER 14 Mov [(r 3)]  [(r 1)])
    (OPER 15 Mov [(r 10)]  [(i 10)])
    (OPER 16 Div_I [(r 11)]  [(r 1)(r 10)])
    (OPER 17 Mov [(r 1)]  [(r 11)])
    (OPER 18 Mov [(r 12)]  [(i 10)])
    (OPER 19 Mul_I [(r 13)]  [(r 1)(r 12)])
    (OPER 20 Sub_I [(r 14)]  [(r 3)(r 13)])
    (OPER 21 Mov [(r 2)]  [(r 14)])
    (OPER 22 Mov [(r 15)]  [(i 0)])
    (OPER 23 GT [(r 16)]  [(r 1)(r 15)])
    (OPER 24 BEQ []  [(r 16)(i 0)(bb 7)])
  )
  (BB 6
    (OPER 25 Pass []  [(r 1)] [(PARAM_NUM 0)])
    (OPER 26 JSR []  [(s printInt)] [(numParams 1)])
    (OPER 27 Mov [(r 17)]  [(m RetReg)])
  )
  (BB 7
    (OPER 28 Pass []  [(r 2)] [(PARAM_NUM 0)])
    (OPER 29 JSR []  [(s putDigit)] [(numParams 1)])
    (OPER 30 Mov [(r 18)]  [(m RetReg)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
)
(FUNCTION  fact  [(int x)]
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 2)]  [(i 1)])
    (OPER 5 GT [(r 3)]  [(r 1)(r 2)])
    (OPER 6 BEQ []  [(r 3)(i 0)(bb 5)])
  )
  (BB 4
    (OPER 7 Mov [(r 4)]  [(i 1)])
    (OPER 8 Sub_I [(r 5)]  [(r 1)(r 4)])
    (OPER 9 Pass []  [(r 5)] [(PARAM_NUM 0)])
    (OPER 10 JSR []  [(s fact)] [(numParams 1)])
    (OPER 11 Mov [(r 6)]  [(m RetReg)])
    (OPER 12 Mul_I [(r 7)]  [(r 1)(r 6)])
    (OPER 13 Mov [(m RetReg)]  [(r 7)])
    (OPER 14 Jmp []  [(bb 1)])
  )
  (BB 9
  )
  (BB 6
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
  (BB 5
    (OPER 15 Mov [(r 8)]  [(i 0)])
    (OPER 16 LT [(r 9)]  [(r 1)(r 8)])
    (OPER 17 BEQ []  [(r 9)(i 0)(bb 8)])
    (OPER 39 Jmp []  [(bb 6)])
  )
  (BB 7
    (OPER 18 Mov [(r 10)]  [(i 66)])
    (OPER 19 Pass []  [(r 10)] [(PARAM_NUM 0)])
    (OPER 20 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 21 Mov [(r 11)]  [(m RetReg)])
    (OPER 22 Mov [(r 12)]  [(i 65)])
    (OPER 23 Pass []  [(r 12)] [(PARAM_NUM 0)])
    (OPER 24 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 25 Mov [(r 13)]  [(m RetReg)])
    (OPER 26 Mov [(r 14)]  [(i 68)])
    (OPER 27 Pass []  [(r 14)] [(PARAM_NUM 0)])
    (OPER 28 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 29 Mov [(r 15)]  [(m RetReg)])
    (OPER 30 Mov [(r 16)]  [(i 0)])
    (OPER 31 Mov [(r 17)]  [(i 1)])
    (OPER 32 Sub_I [(r 18)]  [(r 16)(r 17)])
    (OPER 33 Mov [(m RetReg)]  [(r 18)])
    (OPER 34 Jmp []  [(bb 1)])
  )
  (BB 8
    (OPER 35 Mov [(r 19)]  [(i 1)])
    (OPER 36 Mov [(m RetReg)]  [(r 19)])
    (OPER 37 Jmp []  [(bb 1)])
    (OPER 38 Jmp []  [(bb 9)])
  )
)
(FUNCTION  main  []
  (BB 2
    (OPER 3 Func_Entry []  [])
  )
  (BB 3
    (OPER 4 Mov [(r 2)]  [(i 5)])
    (OPER 5 Mov [(r 1)]  [(r 2)])
    (OPER 6 Pass []  [(r 1)] [(PARAM_NUM 0)])
    (OPER 7 JSR []  [(s fact)] [(numParams 1)])
    (OPER 8 Mov [(r 3)]  [(m RetReg)])
    (OPER 9 Pass []  [(r 3)] [(PARAM_NUM 0)])
    (OPER 10 JSR []  [(s printInt)] [(numParams 1)])
    (OPER 11 Mov [(r 4)]  [(m RetReg)])
    (OPER 12 Mov [(r 5)]  [(i 10)])
    (OPER 13 Pass []  [(r 5)] [(PARAM_NUM 0)])
    (OPER 14 JSR []  [(s putchar)] [(numParams 1)])
    (OPER 15 Mov [(r 6)]  [(m RetReg)])
    (OPER 16 Mov [(r 7)]  [(i 0)])
    (OPER 17 Mov [(m RetReg)]  [(r 7)])
    (OPER 18 Jmp []  [(bb 1)])
  )
  (BB 1
    (OPER 1 Func_Exit []  [])
    (OPER 2 Return []  [(m RetReg)])
  )
)
